#pragma config(Hubs,  S3, HTServo,  none,     none,     none)
#pragma config(Hubs,  S4, HTMotor,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Sensor, S1,     SENSOR_IR,      sensorI2CCustom)
#pragma config(Sensor, S2,     SENSOR_GYRO,    sensorI2CHiTechnicGyro)
#pragma config(Sensor, S3,     ,               sensorI2CMuxController)
#pragma config(Sensor, S4,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S4_C1_1,     motorFL,       tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S4_C1_2,     motorFR,       tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S4_C2_1,     motorBL,       tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S4_C2_2,     motorBR,       tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S4_C3_1,     liftL,         tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S4_C3_2,     liftR,         tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S4_C4_1,     flip,          tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S4_C4_2,     motorI,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S3_C1_1,    servoL,               tServoStandard)
#pragma config(Servo,  srvo_S3_C1_2,    servoR,               tServoStandard)
#pragma config(Servo,  srvo_S3_C1_3,    liftServoL,           tServoStandard)
#pragma config(Servo,  srvo_S3_C1_4,    liftServoR,           tServoStandard)
#pragma config(Servo,  srvo_S3_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S3_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "drivers\hitechnic-gyro.h";
#include "libs.h";
task main()
{
	int base = 0;
	string basektpos = "Disactivated";
	nMotorEncoder[motorFL] = 0;
	nMotorEncoder[motorFR] = 0;
	nMotorEncoder[flip] = 0;
	while (true) {
		while (base == 0) {
			displayTextLine(0, "Lift");
			displayTextLine(1, "Lift L: %6i", nMotorEncoder[liftL]);
			displayTextLine(2, "Lift R: %6i", nMotorEncoder[liftR]);
			displayTextLine(3, "");
			displayTextLine(4, "");
			displayTextLine(5, "");
			displayTextLine(6, "");
			while (nNxtButtonPressed == 1) {
				motor[liftL] = 100;
				motor[liftR] = 100;
			}
			while (nNxtButtonPressed == 2) {
				motor[liftL] = -70;
				motor[liftR] = -70;
			}
			motor[liftL] = 0;
			motor[liftR] = 0;
			if (nNxtButtonPressed == 3) {
				base++;
				delay(500);
			}
		}
		while (base == 1) {
			displayTextLine(0, "Base");
			displayTextLine(1, "EncoderFL: %6i", nMotorEncoder[motorFL]);
			displayTextLine(2, "EncoderFR: %6i", nMotorEncoder[motorFR]);
			displayTextLine(3, "EncoderBL: %6i", nMotorEncoder[motorBL]);
			displayTextLine(4, "EncoderBR: %6i", nMotorEncoder[motorBR]);
			displayTextLine(5, "Encdr Avg: %6i", getEncoderAverage());
			while (nNxtButtonPressed == 1) {
				motor[motorFL] = 100;
				motor[motorFR] = 100;
				motor[motorBL] = 100;
				motor[motorBR] = 100;
			}
			while (nNxtButtonPressed == 2) {
				motor[motorFL] = -100;
				motor[motorFR] = -100;
				motor[motorBL] = -100;
				motor[motorBR] = -100;
			}
			displayTextLine(6, "GyroROT: %2i", HTGYROreadRot(SENSOR_GYRO));
			motor[motorFL] = 0;
			motor[motorBL] = 0;
			motor[motorBR] = 0;
			motor[motorFR] = 0;
			if (nNxtButtonPressed == 3) {
				base++;
				delay(500);
			}
		}
		while (base == 2) {
			displayTextLine(0, "Flinger Flanger");
			displayTextLine(1, "Flip: %6i", nMotorEncoder[flip]);
			displayTextLine(2, "");
			displayTextLine(3, "");
			displayTextLine(4, "");
			displayTextLine(5, "");
			displayTextLine(6, "");
			while (nNxtButtonPressed == 1) {
				motor[flip] = 100;
			}
			while (nNxtButtonPressed == 2) {
				motor[flip] = -100;
			}
			motor[flip] = 0;
			if (nNxtButtonPressed == 3) {
				base++;
				delay(500);
			}
		}
		while (base == 3) {
			displayTextLine(0, "Servo");
			displayTextLine(1, "%5s", basektpos);
			displayTextLine(2, "");
			displayTextLine(3, "");
			displayTextLine(4, "");
			displayTextLine(5, "");
			displayTextLine(6, "");
			if (nNxtButtonPressed == 1) {
				servo[liftServoL] = 100;
				servo[liftServoR] = 155;
				basektpos = "X";
			}
			if (nNxtButtonPressed == 2) {
				servo[liftServoL] = 230;
				servo[liftServoR] = 25;
				basektpos = "A";
			}
			if (nNxtButtonPressed == 3) {
				base++;
				delay(500);
			}
		while (base == 4) {
			displayTextLine(0, "Servo Latches");
			displayTextLine(1, "");
			displayTextLine(2, "");
			displayTextLine(3, "");
			displayTextLine(4, "");
			displayTextLine(5, "");
			displayTextLine(6, "");
			if (nNxtButtonPressed == 1) {
				latch(false);

			}
			if (nNxtButtonPressed == 2) {
				latch(true);
			}
			if (nNxtButtonPressed == 3) {
				base = 0;
				delay(500);
			}
		}
		}
	}
	while(true){}
}
