#pragma config(Sensor, S1,     HTSPB,          sensorI2CCustom9V)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "hitechnic-superpro.h"
/*
Command numbers correlate with different functions compiled to the Arduino
command 1: tell the arduino to calculate heading (input)
command 2: receive the first half of heading from the arduino (output)
command 3: receive second half of the heading

*/

signed int result;//Global in order to read on NXT screen

//sends a command to the Arduino over S0-3, and gets data frorm B0-7
int sendArduinoCommand(unsigned char command)
{
	HTSPBsetupIO(HTSPB, 0xFF); //sets B0-7 to output
	HTSPBwriteStrobe(HTSPB, command); // send the command via S0-3
	if (command >= 2)
	{
		HTSPBsetupIO(HTSPB, 0x00); // sets BO-7 to input so that it can receive
		result = HTSPBreadIO(HTSPB, 0xFF);
	}
	return result;
}

int getMPUHeading()
{
	signed int add1 = sendArduinoCommand(2);
	nxtDisplayBigTextLine(4, "%d", add1);
	int heading = add1 * 2;
	if(heading > 180)
		heading = heading - 360;
	return heading;
}

task main()
{
	while(true){
		getMPUHeading();
		nxtDisplayBigTextLine(1, "%d", getMPUHeading());
	}
}
