#pragma config(Sensor, S1,     HTSPB,          sensorI2CCustom9V)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "hitechnic-superpro.h"
/*
Command numbers correlate with different functions compiled to the Arduino
command 1: tell the arduino to calculate heading (input)
command 2: tell the arduino to get raw value of z axis (input)
command 3: receive the heading from the arduino (output)

*/

int result;

//sends a command to the Arduino over S0-3, and gets data frorm B0-7
unsigned char sendArduinoCommand(unsigned char command)
{
		HTSPBsetupIO(HTSPB, 0xFF); //sets B0-7 to output
		HTSPBwriteStrobe(HTSPB, command); // send the command via S0-3
	if (command >= 2)
	{
		HTSPBsetupIO(HTSPB, 0x00); // sets BO-7 to input so that it can receive
		result = HTSPBreadIO(HTSPB, 0xFF); //Do they read in the same order as Arduino sends?
		return result;
	}
}

task main()
{
	wait10Msec(1000);
	sendArduinoCommand(3);
}
